# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative ""../lib/custom_download_strategy""
class SampleGoConsumer < Formula
  desc "Kafka Consumer for Protobuf"
  homepage "https://github.com/Khushbukela/sample-go-consumer"
  version "200.0.24"

  on_macos do
    url "https://github.com/khushbukela/sample-go-consumer/releases/download/200.0.24/sample-go-consumer_Darwin_all.zip", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "7f19232d294080198c12870231b61bd53f800c434d4ca49a1c1a74b9d0be5e8f"

    def install
      bin.install "sample-go-consumer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/200.0.24/sample-go-consumer_Linux_arm64.zip", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "630171dad0f41ba5f43b80a062df4d65894a0996f158ab61b3e3b30056426559"

      def install
        bin.install "sample-go-consumer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khushbukela/sample-go-consumer/releases/download/200.0.24/sample-go-consumer_Linux_x86_64.zip", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f786c6e776ca7126e157b9f1c303540ec8dc7a2ff334045202d59552225529f8"

      def install
        bin.install "sample-go-consumer"
      end
    end
  end
end
